##
{{- if .Values.certManager }}
{{- if and .Values.global.dynamics (hasKey .Values.global "dynamics")}}
certManager:
  dynamics:
    common:
      baseFqdn: {{ .Values.certManager.dynamics.common.baseFqdn }}
    {{- if .Values.certManager.dynamics.isSelfsigned }}
    isSelfsigned:
      create: {{ .Values.certManager.dynamics.isSelfsigned.create | default false }}
    {{- end }}
    {{- if .Values.certManager.dynamics.isCa }}
    isCa:
      create: {{ .Values.certManager.dynamics.isCa.create | default false }}
    {{- end }}
{{- end }}
{{- end }}