apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "common.names.namespace" . }}
spec:
  isCA: true
  commonName: "{{ .Values.fqdn }}"
  dnsNames:
    - "{{ .Values.fqdn }}"
    - "*.{{ .Values.fqdn }}"
  duration: 87600h
  secretName: {{ .Values.fqdn }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: cluster-issuer-rootca
    kind: ClusterIssuer
    group: cert-manager.io