openapi: 3.0.3
info:
  title: ros2_oidc
  description: Demo SROS2 app secured with OIDC(Keycloak)
  license:
    name: MIT
    url: https://github.com/rdbox-intec/rdbox_next/blob/main/LICENSE
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: base
- name: ros2_amcl
paths:
  /:
    get:
      tags:
      - base
      operationId: home
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
      x-openapi-router-controller: relaying_party.controllers.base_controller
  /login:
    get:
      tags:
      - base
      operationId: login
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
      x-openapi-router-controller: relaying_party.controllers.base_controller
  /logout:
    get:
      tags:
      - base
      operationId: logout
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
      x-openapi-router-controller: relaying_party.controllers.base_controller
  /gettoken:
    get:
      tags:
      - base
      operationId: get_token
      parameters:
      - name: code
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: session_state
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
            headers:
              x-Authorization:
                schema:
                  type: string
      x-openapi-router-controller: relaying_party.controllers.base_controller
  /ros2:
    get:
      tags:
      - ros2_amcl
      operationId: ros2
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
      x-openapi-router-controller: relaying_party.controllers.base_controller
  /ros2/amcl/come_to_me:
    get:
      tags:
      - ros2_amcl
      operationId: come_to_me
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <html><a href=/login>Login</a></html>
                x-content-type: text/html
      security:
      - AuthBearer: []
      - openId:
        - openid
      x-openapi-router-controller: relaying_party.controllers.ros2_amcl_controller
components:
  schemas: {}
  securitySchemes:
    AuthBearer:
      type: http
      scheme: bearer
      x-bearerInfoFunc: relaying_party.controllers.authorization_controller.check_AuthBearer
    openId:
      type: openIdConnect
      description: "URI to retrieve OpenID Provider settings, defined in OpenID Connect\
        \ Discovery 1.0"
      openIdConnectUrl: https://keycloak.rdbox.172-16-0-132.nip.io/auth/realms/rdbox/.well-known/openid-configuration

