FROM ubuntu:20.04

RUN apt update
RUN apt install -y mesa-utils \
                  libgl1-mesa-glx \
                  libgl1-mesa-dri \
                  mesa-utils-extra \
                  xserver-xorg-core \
                  libglx-mesa0 \
                  mesa-vulkan-drivers \
                  xserver-xorg-video-all


