#!/usr/bin/env bash
set -euo pipefail

###############################################################################
## A Kick script to use the RDBOX with Docker
## - Run it on **HostOS**
## Style: https://google.github.io/styleguide/shellguide.html
###############################################################################

function main() {
  ## Run in the Host
  ##
  initial_directory
  ## Run in the Container
  ##
  if [[ -f /.dockerenv ]]; then
    ### Note
    ### Probably any Container can be used
    ### References: https://github.com/moby/moby/blob/master/daemon/initlayer/setup_unix.go#L30
    "/rdbox/main.rdbox" "$@"
    return $?
  fi
  ## Run in the Host
  ##
  local os_name
  os_name=$(getOsNameAtHost)
  if [[ "${os_name}" == "MacOS" ]]; then
    getNetworkInfo
      ### NOTE
      ### Get a network info and Export ones
      ### RDBOX_NETWORK_DEFULT_NIC_NAME, RDBOX_NETWORK_DEFULT_NIC_IPV4, RDBOX_NETWORK_DEFULT_NIC_IPV6
    docker run -it --rm \
      -p 8000:8000 \
      -v "$(pwd)":/rdbox \
      -v "${HOME}"/.kube:/home/ubuntu/.kube \
      -v "${RDBOX_WORKDIR_OF_WORK_BASE}":"${RDBOX_WORKDIR_OF_WORK_BASE}" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e KUBECONFIG=/home/ubuntu/.kube/config \
      -e RDBOX_NETWORK_DEFULT_NIC_NAME="${RDBOX_NETWORK_DEFULT_NIC_NAME}" \
      -e RDBOX_NETWORK_DEFULT_NIC_IPV4="${RDBOX_NETWORK_DEFULT_NIC_IPV4}" \
      -e RDBOX_NETWORK_DEFULT_NIC_IPV6="${RDBOX_NETWORK_DEFULT_NIC_IPV6}" \
      -e RDBOX_ESSENTIALS_A_POLICY_TO_ISSUE_CERT="${RDBOX_ESSENTIALS_A_POLICY_TO_ISSUE_CERT:-new}" \
      -e LOCAL_UID="$(id -u "${USER}")" \
      -e LOCAL_GID="$(id -g "${USER}")" \
      -e RDBOX_WORKDIR_OF_WORK_BASE="${RDBOX_WORKDIR_OF_WORK_BASE}" \
      -e RDBOX_WORKDIR_OF_DATA_BASE="${RDBOX_WORKDIR_OF_DATA_BASE}" \
      rdbox/docker:20.10 \
      "/rdbox/main.rdbox" "$@"
  elif [[ "${os_name}" == "Linux" ]]; then
    mkdir -p "${HOME}"/.cache/helm
    mkdir -p "${HOME}"/.config/helm
    mkdir -p "${HOME}"/.local/share/helm
    docker run -it --rm \
      --network host \
      -v "$(pwd)":/rdbox \
      -v "${HOME}"/.kube:/home/ubuntu/.kube \
      -v "${RDBOX_WORKDIR_OF_WORK_BASE}":"${RDBOX_WORKDIR_OF_WORK_BASE}" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v "${HOME}"/.cache/helm:/home/ubuntu/.cache/helm \
      -v "${HOME}"/.cache/helm:/home/ubuntu/.config/helm \
      -v "${HOME}"/.cache/helm:/home/ubuntu/.local/helm \
      -e KUBECONFIG=/home/ubuntu/.kube/config \
      -e RDBOX_ESSENTIALS_A_POLICY_TO_ISSUE_CERT="${RDBOX_ESSENTIALS_A_POLICY_TO_ISSUE_CERT:-new}" \
      -e LOCAL_UID="$(id -u "${USER}")" \
      -e LOCAL_GID="$(id -g "${USER}")" \
      -e RDBOX_WORKDIR_OF_WORK_BASE="${RDBOX_WORKDIR_OF_WORK_BASE}" \
      -e RDBOX_WORKDIR_OF_DATA_BASE="${RDBOX_WORKDIR_OF_DATA_BASE}" \
      rdbox/docker:20.10 \
      "/rdbox/main.rdbox" "$@"
  fi
  return $?
}

function initial_directory() {
  local work_dir
  work_dir=${RDBOX_WORKDIR_OF_WORK_BASE:-${HOME}/crobotics}
  RDBOX_WORKDIR_OF_WORK_BASE=${work_dir}
  export RDBOX_WORKDIR_OF_WORK_BASE="${RDBOX_WORKDIR_OF_WORK_BASE}"
  export RDBOX_WORKDIR_OF_DATA_BASE="${RDBOX_WORKDIR_OF_WORK_BASE}_data"
  mkdir -p "${RDBOX_WORKDIR_OF_WORK_BASE}"
  mkdir -p "${RDBOX_WORKDIR_OF_DATA_BASE}"
  mkdir -p "${HOME}/.kube"
}

## Set the base directory for RDBOX scripts!!
##
RDBOX_WORKDIR_OF_SCRIPTS_BASE=${RDBOX_WORKDIR_OF_SCRIPTS_BASE:-$(cd "$(dirname "$0")" || exit 1; pwd)}
RDBOX_WORKDIR_OF_SCRIPTS_BASE=$(printf %q "$RDBOX_WORKDIR_OF_SCRIPTS_BASE")
export RDBOX_WORKDIR_OF_SCRIPTS_BASE=$RDBOX_WORKDIR_OF_SCRIPTS_BASE
  ### EXTRAPOLATION
source "${RDBOX_WORKDIR_OF_SCRIPTS_BASE}/modules/libs/common.bash"
main "$@"
exit $?