# rdbox.local/v1beta1
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.24.3@sha256:e812632818ae40cee2a9a22123ceb075f8550d132f860d67e2c35b7caf0fa215
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0:10249
  - |
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
    etcd:
      local:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
- role: worker
  image: kindest/node:v1.24.3@sha256:e812632818ae40cee2a9a22123ceb075f8550d132f860d67e2c35b7caf0fa215
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32022
    hostPort: 32022
    protocol: TCP
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  extraMounts:
  - containerPath: /fromhost
    hostPath: /tmp/tocontainer
