# Default values for metallb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Refer to https://metallb.universe.tf/configuration/ for
# available options.
crds:
  enabled: true