apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: ubuntu/nginx
    name: nginx
    volumeMounts:
    - mountPath: /fromhost
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /fromhost
      type: Directory


