#!/usr/bin/env bash
set -euo pipefail

###############################################################################
## A Kick script to use the RDBOX with Docker
## - Run it on **HostOS**
###############################################################################

function main() {
  RDBOX_TYPE_OF_SECRET_OPERATION=${RDBOX_TYPE_OF_SECRET_OPERATION:-new}
  os_name=$(getOsNameAtHost)
  if [[ "${os_name}" == "MacOS" ]]; then
    getNetworkInfo
      ### NOTE
      ### Get a network info and Export ones
      ### RDBOX_NETWORK_DEFULT_NIC_NAME, RDBOX_NETWORK_DEFULT_NIC_IPV4, RDBOX_NETWORK_DEFULT_NIC_IPV6
    docker run -it --rm \
      -p 8000:8000 \
      -v "$(pwd)":/rdbox \
      -v "${HOME}"/.kube:/tmp/.kube \
      -v "${HOME}"/crobotics:/tmp/crobotics \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e KUBECONFIG=/tmp/.kube/config \
      -e RDBOX_NETWORK_DEFULT_NIC_NAME="${RDBOX_NETWORK_DEFULT_NIC_NAME}" \
      -e RDBOX_NETWORK_DEFULT_NIC_IPV4="${RDBOX_NETWORK_DEFULT_NIC_IPV4}" \
      -e RDBOX_NETWORK_DEFULT_NIC_IPV6="${RDBOX_NETWORK_DEFULT_NIC_IPV6}" \
      -e RDBOX_TYPE_OF_SECRET_OPERATION="${RDBOX_TYPE_OF_SECRET_OPERATION}" \
      -e LOCAL_UID="$(id -u "${USER}")" \
      -e LOCAL_GID="$(id -g "${USER}")" \
      rdbox/docker:20.10 \
      "/rdbox/main.rdbox" "$@"
  elif [[ "${os_name}" == "Linux" ]]; then
    docker run -it --rm \
      --network host \
      -v "$(pwd)":/rdbox \
      -v "${HOME}"/.kube:/tmp/.kube \
      -v "${HOME}"/crobotics:/tmp/crobotics \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e KUBECONFIG=/tmp/.kube/config \
      -e RDBOX_TYPE_OF_SECRET_OPERATION="${RDBOX_TYPE_OF_SECRET_OPERATION}" \
      -e LOCAL_UID="$(id -u "${USER}")" \
      -e LOCAL_GID="$(id -g "${USER}")" \
      rdbox/docker:20.10 \
      "/rdbox/main.rdbox" "$@"
  fi
  return $?
}

## Set the base directory for RDBOX scripts!!
##
RDBOX_WORKDIR_OF_SCRIPTS_BASE=${RDBOX_WORKDIR_OF_SCRIPTS_BASE:-$(cd "$(dirname "$0")" || exit 1; pwd)}
RDBOX_WORKDIR_OF_SCRIPTS_BASE=$(printf %q "$RDBOX_WORKDIR_OF_SCRIPTS_BASE")
export RDBOX_WORKDIR_OF_SCRIPTS_BASE=$RDBOX_WORKDIR_OF_SCRIPTS_BASE
  ### EXTRAPOLATION
source "${RDBOX_WORKDIR_OF_SCRIPTS_BASE}/modules/libs/common.bash"
main "$@"
exit $?