#!/usr/bin/env bash
set -euo pipefail

###############################################################################
## A Kick script to use the RDBOX with Docker
## - Run it on **HostOS**
###############################################################################

function main() {
  getNetworkInfo
    ### NOTE
    ### Get a network info and Export ones
    ### RDBOX_NETWORK_DEFULT_NIC_NAME, RDBOX_NETWORK_DEFULT_NIC_IPV4, RDBOX_NETWORK_DEFULT_NIC_IPV6
  RDBOX_TYPE_OF_SECRET_OPERATION=${RDBOX_TYPE_OF_SECRET_OPERATION:-new}
  docker run -it --rm \
    -p 8000:8000 \
    -v "$(pwd)":/rdbox \
    -v "${HOME}"/.kube/:/root/.kube \
    -v "${HOME}"/crobotics/:/root/crobotics \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e RDBOX_NETWORK_DEFULT_NIC_NAME="${RDBOX_NETWORK_DEFULT_NIC_NAME}" \
    -e RDBOX_NETWORK_DEFULT_NIC_IPV4="${RDBOX_NETWORK_DEFULT_NIC_IPV4}" \
    -e RDBOX_NETWORK_DEFULT_NIC_IPV6="${RDBOX_NETWORK_DEFULT_NIC_IPV6}" \
    -e RDBOX_TYPE_OF_SECRET_OPERATION="${RDBOX_TYPE_OF_SECRET_OPERATION}" \
    rdbox/docker:20.10 \
    "/rdbox/main.rdbox" "$@"
  return $?
}

## Set the base directory for RDBOX scripts!!
##
RDBOX_WORKDIR_OF_SCRIPTS_BASE=${RDBOX_WORKDIR_OF_SCRIPTS_BASE:-$(cd "$(dirname "$0")" || exit 1; pwd)}
RDBOX_WORKDIR_OF_SCRIPTS_BASE=$(printf %q "$RDBOX_WORKDIR_OF_SCRIPTS_BASE")
export RDBOX_WORKDIR_OF_SCRIPTS_BASE=$RDBOX_WORKDIR_OF_SCRIPTS_BASE
  ### EXTRAPOLATION
source "${RDBOX_WORKDIR_OF_SCRIPTS_BASE}/modules/libs/common.bash"
main "$@"
exit $?