## NOTICE
#
# Due to the scope and complexity of this chart, all possible values are
# not documented in this file. Extensive documentation is available.
#
# Please read the docs: https://docs.gitlab.com/charts/
#
# Because properties are regularly added, updated, or relocated, it is
# _strongly suggest_ to not "copy and paste" this YAML. Please provide
# Helm only those properties you need, and allow the defaults to be
# provided by the version of this chart at the time of deployment.

## Advanced Configuration
## https://docs.gitlab.com/charts/advanced
#
# Documentation for advanced configuration, such as
# - External PostgreSQL
# - External Gitaly
# - External Redis
# - External NGINX
# - External Object Storage providers
# - PersistentVolume configuration

## The global properties are used to configure multiple charts at once.
## https://docs.gitlab.com/charts/charts/globals
global:
  ## https://docs.gitlab.com/charts/installation/deployment#deploy-the-community-edition
  edition: ee
  ## https://docs.gitlab.com/charts/charts/globals#configure-host-settings
  hosts:
    domain: rdbox.127-0-0-1.nip.io
    https: true
  ## https://docs.gitlab.com/charts/charts/globals#configure-ingress-settings
  ingress:
    apiVersion: 'networking.k8s.io/v1'
    configureCertmanager: false
    class: ambassador
    enabled: true
    tls:
      enabled: true
      secretName: rdbox-common-tls
    path: '/'
    pathType: Prefix
    provider: ambassador
  ## https://docs.gitlab.com/charts/charts/globals#configure-minio-settings
  minio:
    enabled: true
    credentials: {}


##-------------------------------------------------------------------------------------------
## End of global
##-------------------------------------------------------------------------------------------
upgradeCheck:
  enabled: true
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
      operator: "Exists"

## Installation & configuration of jetstack/cert-manager
## See requirements.yaml for current version
certmanager:
  # Install cert-manager chart. Set to false if you already have cert-manager
  # installed or if you are not using cert-manager.
  install: false

## https://docs.gitlab.com/charts/charts/nginx/
## https://docs.gitlab.com/charts/architecture/decisions#nginx-ingress
## Installation & configuration of charts/ingress-nginx:
nginx-ingress:
  enabled: false

## Installation & configuration of stable/prometheus
## See requirements.yaml for current version
prometheus:
  install: false

## Configuration of Redis
## https://docs.gitlab.com/charts/architecture/decisions#redis
## https://docs.gitlab.com/charts/installation/deployment.html#redis
redis:
  install: true
  master:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    persistence:
      storageClass: standard
      size: 8Gi

## Installation & configuration of stable/prostgresql
## See requirements.yaml for current version
postgresql:
  install: true
  persistence:
    storageClass: standard
    size: 8Gi

## Installation & configuration charts/registry
## https://docs.gitlab.com/charts/architecture/decisions#registry
## https://docs.gitlab.com/charts/charts/registry/
registry:
  enabled: true
  hpa:
    minReplicas: 1
    maxReplicas: 1

## Automatic shared secret generation
## https://docs.gitlab.com/charts/installation/secrets
## https://docs.gitlab.com/charts/charts/shared-secrets.html
shared-secrets:
  enabled: true
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
      operator: "Exists"

## Installation & configuration of gitlab/gitlab-runner
## See requirements.yaml for current version
gitlab-runner:
  install: true
  rbac:
    create: true
  runners:
    locked: false
    config: |
      [[runners]]
        name = "docker"
        pre_build_script = """
        apk update
        apk add ca-certificates
        rm -rf /var/cache/apk/*
        cat $CI_SERVER_TLS_CA_FILE > /usr/local/share/ca-certificates/ca.crt
        update-ca-certificates --fresh
        """
        [runners.kubernetes]
          image = "ubuntu:20.04"
          privileged = true
          [[runners.kubernetes.services]]
            name = "docker:20.10.12-dind"
            entrypoint = ['/bin/sh', '-c', 'echo "$CA_CERTIFICATE" > /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates && dockerd-entrypoint.sh || exit']
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-certs"
            mount_path = "/certs/client"
            medium = "Memory"
          [[runners.kubernetes.volumes.pvc]]
            name = "r2s2-resident-pvc"
            mount_path = "/data"
        [runners.cache]
          Type = "s3"
          Path = "gitlab-runner"
          Shared = true
          [runners.cache.s3]
            ServerAddress = {{ include "gitlab-runner.cache-tpl.s3ServerAddress" . }}
            BucketName = "runner-cache"
            BucketLocation = "us-east-1"
            Insecure = false
  certsSecretName: rdbox-common-tls

## Installation & configuration of stable/grafana
## See requirements.yaml for current version
## Controlled by `global.grafana.enabled`
# grafana:

## Settings for individual sub-charts under GitLab
## Note: Many of these settings are configurable via globals
gitlab:
## https://docs.gitlab.com/charts/charts/gitlab/toolbox
  toolbox:
    replicas: 1
    antiAffinityLabels:
      matchLabels:
        app: 'gitaly'
## https://docs.gitlab.com/charts/charts/gitlab/webservice
  webservice:
    enabled: true
    helmTests:
      enabled: false
    minReplicas: 1
    maxReplicas: 2
    resources:
      limits:
        memory: 3.0G
      requests:
        cpu: 100m
        memory: 900M
    workhorse:
      resources:
        requests:
          cpu: 10m
          memory: 10M
## https://docs.gitlab.com/charts/charts/gitlab/migrations
#   migrations:
#     enabled: false
## https://docs.gitlab.com/charts/charts/gitlab/sidekiq
  sidekiq:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    resources:
      limits:
        memory: 5G
      requests:
        cpu: 50m
        memory: 625M
# https://docs.gitlab.com/charts/charts/gitlab/gitaly
  gitaly:
    persistence:
      size: 8Gi
      storageClass: standard
## https://docs.gitlab.com/charts/charts/gitlab/gitlab-shell
  gitlab-shell:
    enabled: true
    minReplicas: 1


##-------------------------------------------------------------------------------------------
## The following are additional settings.
##-------------------------------------------------------------------------------------------
## Using MinIO for Object storage
## https://docs.gitlab.com/charts/charts/globals#configure-minio-settings
## https://docs.gitlab.com/charts/charts/minio/index.html
minio:
  resources:
    requests:
      memory: 64Mi
      cpu: 10m
  persistence:
    size: 3Gi
    storageClass: standard
