####### Component scraping
kubeScheduler:
  service:
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeControllerManager:
  service:
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381

####### kube-prometheus-stack
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ambassador
    path: /grafana/
    hosts:
      - internal.rdbox.172-16-0-110.nip.io
    tls:
      - secretName: rdbox-common-tls
        hosts:
          - internal.rdbox.172-16-0-110.nip.io
  grafana.ini:
    server:
      domain: internal.rdbox.172-16-0-110.nip.io
      root_url: "https://internal.rdbox.172-16-0-110.nip.io/grafana/"
      serve_from_sub_path: true
    live:
      max_connections: -1                   # Temporarily disable WebSocket. Will be done soon.
                                            # https://grafana.com/docs/grafana/latest/administration/configuration/#max_connections
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ambassador
    paths:
      - /prometheus/
    hosts:
      - internal.rdbox.172-16-0-110.nip.io
    tls:
      - secretName: rdbox-common-tls
        hosts:
          - internal.rdbox.172-16-0-110.nip.io
  prometheusSpec:
    externalUrl: /prometheus/
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ambassador
    paths:
      - /alert-manager/
    hosts:
      - internal.rdbox.172-16-0-110.nip.io
    tls:
      - secretName: rdbox-common-tls
        hosts:
          - internal.rdbox.172-16-0-110.nip.io
  alertmanagerSpec:
    externalUrl: "https://internal.rdbox.172-16-0-110.nip.io/alert-manager/"