# https://cert-manager.io/docs/usage/certificate/
ambassador:
  di:
    certificate:
      duration: 87600h
      privateKey:
        algorithm: RSA
        size: 4096
      # subject:
      #   organizations: INTEC Inc.
      #   countries: JP
      #   organizationalUnits: ATI
      #   localities: Koto-Ku
      #   provinces: Tokyo
      #   streetAddresses: Toyosu
      #   postalCodes: 135-0061
      #   serialNumber: A20D27E4-1863-4BD5-9EF1-B25C38D76C88