# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

createDevPortalMappings: false

# Emissary Chart Values.
# all values under emissary-ingress key are passed to [the emissary chart](https://github.com/emissary-ingress/emissary/blob/master/charts/emissary-ingress/README.md)
# Example:
# setting `emissary-ingress.service.type=NodePort` will pass `service.type=NodePort` to the underlying emissary chart
emissary-ingress:
  createDefaultListeners: true
  deploymentTool: amb-oper-kind
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Equal
      effect: NoSchedule
  replicaCount: 1
  deploymentStrategy:
    type: Recreate
  nodeSelector:
    ingress-ready: "true"
  service:
    type: NodePort
    ports:
    - name: http
      port: 80
      hostPort: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      hostPort: 443
      targetPort: 8443
      protocol: TCP
    - name: ssh
      port: 32022
      hostPort: 32022
      targetPort: 32022
      protocol: TCP

# Ambassador ships with a basic redis instance. Configure the deployment with the options below.
redis:
  create: true
  nodeSelector:
    ingress-ready: "true"