##
{{if (default .Values.global.manifests false)}}
{{if (default .Values.certManager.isSelfsigned false)}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-selfsigned-{{ .Release.Name }}.{{ .Values.global.baseFqdn }}
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: jetstack.cert-manager
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
spec:
  isCA: true
  commonName: "{{ .Values.global.baseFqdn }}"
  dnsNames:
    - {{ .Values.global.baseFqdn }}
    - "*.{{ .Values.global.baseFqdn }}"
  duration: {{ .Values.certificate.duration }}
  secretName: {{ .Values.global.baseFqdn }}
  {{- if .Values.certificate.privateKey }}
  privateKey: {{- include "common.tplvalues.render" ( dict "value" .Values.certificate.privateKey "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.certificate.subject }}
  subject: {{- include "common.tplvalues.render" ( dict "value" .Values.certificate.subject "context" $) | nindent 4 }}
  {{- end }}
  issuerRef:
    name: cluster-issuer-selfsigned-{{ .Release.Name }}
    kind: ClusterIssuer
    group: cert-manager.io
{{ end }}
{{ end }}