##
{{- if .Values.grafana }}
{{- if and .Values.global.manifests (hasKey .Values.global "manifests")}}
{{- if .Values.grafana.dynamics.ingress }}
{{- if and .Values.grafana.dynamics.ingress.create (hasKey .Values.grafana.dynamics.ingress "create")}}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: "{{ .Values.grafana.dynamics.main.hostname }}"
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.kube-grafana
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
spec:
  host: {{ .Values.grafana.dynamics.main.fqdn }}
  prefix: /
  allow_upgrade:
  - spdy/3.1
  - websocket
  service: "{{ .Values.grafana.dynamics.ingress.service }}"
  timeout_ms: 0
{{- end }}
{{- end }}
{{- end }}
{{- end }}