##
{{- if .Values.impersonator }}
{{- if and .Values.global.manifests (hasKey .Values.global "manifests")}}
{{- if .Values.impersonator.dynamics.k8ssso.endpoint }}
{{- if .Values.impersonator.dynamics.k8ssso.endpoint.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.impersonator.dynamics.k8ssso.hostname }}
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.impersonator.dynamics.k8ssso.hostname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.impersonator.dynamics.k8ssso.hostname }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}