##
{{- if .Values.ambassador }}
{{- if and .Values.global.manifests (hasKey .Values.global "manifests")}}
{{- if .Values.ambassador.dynamics.k8ssso.endpoint }}
{{- if .Values.ambassador.dynamics.k8ssso.endpoint.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ambassador.dynamics.k8ssso.hostname }}
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
rules:
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
{{- end }}
{{- end }}
{{- end }}
{{- end }}