##
{{- if .Values.keycloak }}
{{- if and .Values.global.manifests (hasKey .Values.global "manifests")}}
{{- if and .Values.keycloak.dynamics.main.rbac (hasKey .Values.keycloak.dynamics.main "rbac")}}
{{- if and .Values.keycloak.dynamics.main.rbac.create (hasKey .Values.keycloak.dynamics.main.rbac "create")}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}:cluster-admin
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}/cluster-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}:admin
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}/admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}:edit
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}/edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}:view
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetAdminGroup }}/view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}:admin
  namespace: {{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}/admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}:edit
  namespace: {{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}/edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-grp:{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}:view
  namespace: {{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: bitnami.keycloak
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
subjects:
- kind: Group
  name: /{{ .Values.keycloak.dynamics.main.rbac.presetRegularGroup }}/view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}
{{- end }}
{{- end }}
{{- end }}